// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJDi4lP1fruyR9GbKifWNWrP_71wc9uWU',
    appId: '1:664485634889:web:6378dcbf28e9704581b098',
    messagingSenderId: '664485634889',
    projectId: 'sleepmind-1705d',
    authDomain: 'sleepmind-1705d.firebaseapp.com',
    storageBucket: 'sleepmind-1705d.firebasestorage.app',
    measurementId: 'G-9YQPC2GFGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv-QR_TxxG07b7jAvsfgjVR-QXKPw-QjA',
    appId: '1:664485634889:android:76ff5f197d59298681b098',
    messagingSenderId: '664485634889',
    projectId: 'sleepmind-1705d',
    storageBucket: 'sleepmind-1705d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxLvHBc986vOCL92cgcQSMuE72Jsp4gwY',
    appId: '1:664485634889:ios:67844c5c180ee8d581b098',
    messagingSenderId: '664485634889',
    projectId: 'sleepmind-1705d',
    storageBucket: 'sleepmind-1705d.firebasestorage.app',
    iosBundleId: 'com.example.sleepMind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxLvHBc986vOCL92cgcQSMuE72Jsp4gwY',
    appId: '1:664485634889:ios:67844c5c180ee8d581b098',
    messagingSenderId: '664485634889',
    projectId: 'sleepmind-1705d',
    storageBucket: 'sleepmind-1705d.firebasestorage.app',
    iosBundleId: 'com.example.sleepMind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJDi4lP1fruyR9GbKifWNWrP_71wc9uWU',
    appId: '1:664485634889:web:e3e0e85caf0c40d481b098',
    messagingSenderId: '664485634889',
    projectId: 'sleepmind-1705d',
    authDomain: 'sleepmind-1705d.firebaseapp.com',
    storageBucket: 'sleepmind-1705d.firebasestorage.app',
    measurementId: 'G-1841DM3CDW',
  );
}
